description = [
["r_associated ","Il est demandé d'énumérer les termes les plus étroitement associés au mot cible... Ce mot vous fait penser à quoi ?"], 
["r_raff_sem ","Raffinement sémantique vers un usage particulier du terme source"], 
["r_syn ","Il est demandé d'énumérer les synonymes ou quasi-synonymes de ce terme. "], 
["r_isa ","Il est demandé d'énumérer les GENERIQUES/hyperonymes du terme. Par exemple, 'animal' et 'mammifère' sont des génériques de 'chat'. "], 
["r_anto ","Il est demandé d'énumérer des contraires du terme. Par exemple, 'chaud' est le contraire de 'froid'. "], 
["r_hypo ","Il est demandé d'énumérer des SPECIFIQUES/hyponymes du terme. Par exemple, 'mouche', 'abeille', 'guêpe' pour 'insecte'. "], 
["r_has_part ","Il faut donner des PARTIES/constituants/éléments (a pour méronymes) du mot cible. Par exemple, 'voiture' a comme parties : 'porte', 'roue', 'moteur',"], 
["r_holo ","Il est demandé d'énumérer des 'TOUT' (a pour holonymes) de l'objet en question. Pour 'main', on aura 'bras', 'corps', 'personne', etc... Le tout est aussi l'ensemble comme 'classe' pour 'élève'. "], 
["r_agent ","L'agent (qu'on appelle aussi le sujet) est l'entité qui effectue l'action, Ou la subit pour des formes passives ou des verbes d'état. Par exemple, dans - Le chat mange la souris -, l'agent est le chat. Des agents typiques de 'courir' peuvent être 'sportif', 'enfant',... (manger r_agent chat) "], 
["r_patient ","Le patient (qu'on appelle aussi l'objet) est l'entité qui subit l'action. Par exemple dans - Le chat mange la souris -, le patient est la souris. Des patients typiques de 'manger' peuvent être 'viande', 'légume', 'pain', ... (manger r_patient pain) "], 
["r_lieu ","Il est demandé d'énumérer les LIEUX typiques où peut se trouver le terme/objet en question. (carotte r_lieu potager)"], 
["r_instr ","L'instrument est l'objet avec lequel on fait l'action. Dans - Il mange sa salade avec une fourchette -, fourchette est l'instrument. Des instruments typiques de 'tuer' peuvent être 'arme', 'pistolet', 'poison', ... (couper r_instr couteau) "], 
["r_carac ","Pour un terme donné, souvent un objet, il est demandé d'en énumérer les Caractéristiques (adjectifs) possibles/typiques. Par exemple, 'liquide', 'froide', 'chaude', pour 'eau'. "], 
["r_lemma ","Le lemme ( par exemple 'mangent a pour lemme 'manger' ; 'avions' a pour lemme 'avion' ou 'avoir'). "], 
["r_family ","Des mots de la même famille lexicale sont demandés (dérivation morphologique, par exemple). Par exemple, pour 'lait' on pourrait mettre 'laitier', 'laitage', 'laiterie', etc. "], 
["r_sentiment ","Pour un terme donné, évoquer des mots liés à des SENTIMENTS ou des EMOTIONS que vous pourriez associer à ce terme. Par exemple, la joie, le plaisir, le dégoût, la peur, la haine, l'amour, l'indifférence, l'envie, avoir peur, horrible, etc. "], 
["r_meaning/glose ","Quels SENS/SIGNIFICATIONS pouvez-vous donner au terme proposé. Il s'agira de termes (des gloses) évoquant chacun des sens possibles, par exemple : 'forces de l'ordre', 'contrat d'assurance', 'police typographique', ... pour 'police'.  "], 
["r_telic_role ","Le rôle télique indique la fonction du nom ou du verbe. Par exemple, couper pour couteau, scier pour scie, etc. C'est le rôle qu'on lui destine communément pour un artéfact, ou bien un rôle qu'on peut attribuer à un objet naturel (réchauffer, éclairer pour soleil). "], 
["r_agentif_role ","De quelle(s) manière(s) peut être CRÉE/CONSTRUIT le terme suivant. On demande des verbes transitifs (le terme en est un complément d'objet) qui DONNENT NAISSANCE à l'entité désignée par le terme, par exemple, 'construire' pour 'maison', 'rédiger'/'imprimer' pour 'livre' ou 'lettre'.  "], 
["r_verbe-action ","du verbe vers l'action. Par exemple, construire -> construction , jardiner -> jardinage . C'est un terme directement dérivé (ayant la même racine). Applicable que pour un verbe et inverse de la relation 34 (action vers verbe). "], 
["r_action-verbe ","de l'action vers le verbe. Par exemple, construction -> construire, jardinage -> jardiner. C'est un terme directement dérivé (ayant la même racine).  Applicable que pour un nom et inverse de la relation 33 (verbe vers action). "], 
["r_conseq ","B (que vous devez donner) est une CONSÉQUENCE possible de A. A et B sont des verbes ou des noms. Exemples : tomber -> se blesser ; faim -> voler ; allumer -> incendie ; négligence --> accident ;"], 
["r_causatif ","B (que vous devez donner) est une CAUSE possible de A. A et B sont des verbes ou des noms. Exemples :se blesser -> tomber ; vol -> pauvreté ; incendie -> négligence ; mort --> maladie ;"], 
["r_adj-verbe ","Pour un adjectif de potentialité/possibilité, son verbe correspondant. Par exemple pour 'lavable' -> 'laver'  "], 
["r_verbe-adj ","Pour un verbe, son adjectif de potentialité/possibilité correspondant. Par exemple pour 'laver' -> 'lavable'  "], 
["r_time ","Donner une valeur temporelle -quel moment- peut-on associer au terme indiqué (par exemple 'dormir' -> nuit, 'bronzer' -> été, 'fatigue' -> 'soir')  "], 
["r_make ","Que peut PRODUIRE le terme ? (par exemple abeille -> miel, usine -> voiture, agriculteur -> blé, moteur -> gaz carbonique ...)  "], 
["r_product_of ","Le terme est le RÉSULTAT/PRODUIT de qui/quoi ? "], 
["r_against ","A quoi le terme suivant S'OPPOSE/COMBAT/EMPÊCHE ? Par exemple, un médicament s'oppose à la maladie. "], 
["r_implication ","Qu'est-ce que le terme implique logiquement ? Par exemple: ronfler implique dormir, courir implique se déplacer, câlin implique contact physique. (attention ce n'est pas la cause ni le but...) "], 
["r_masc ","L'équivalent masculin du terme : lionne --> lion. "], 
["r_fem ","L'équivalent féminin du terme : lion --> lionne. "], 
["r_equiv ","Termes strictement équivalent/identique : acronymes et sigles (PS -> parti socialiste), apocopes (ciné -> cinéma), entités nommées (Louis XIV -> Le roi soleil), etc. (attention il ne s'agit pas de synonyme) "], 
["r_agentive_implication ","Les verbes ou actions qui sont impliqués dans la création de l'objet. Par exemple pour 'construire' un livre, il faut, imprimer, relier, brocher. Il s'agit des étapes nécessaires à la réalisation du rôle agentif. "], 
["r_verb_real ","Pour un verbe, celui qui réalise l'action (par dérivation morphologique). Par exemple, chasser -> chasseur, naviguer -> navigateur. "], 
["r_similar ","Similaire/ressemble à ; par exemple le congre est similaire à une anguille"], 
["r_processus>agent ","Quel est l'acteur de ce processus/événement ? Par exemple, 'nettoyage' peut avoir comme acteur 'technicien de surface'.  "], 
["r_syn_strict ","Termes strictement substituables, pour des termes hors du domaine général, et pour la plupart des noms (exemple : endométriose intra-utérine --> adénomyose) "], 
["r_processus>patient ","Quel est le patient de ce processus/événement ? Par exemple, 'découpe' peut avoir comme patient 'viande'.  "], 
["r_processus>instr ","Quel est l'instrument/moyen de ce processus/événement ?Par exemple, 'découpe' peut avoir comme instrument 'couteau'.  "], 
["r_cible ","Cible de la maladie : myxomatose => lapin, rougeole => enfant,"], 
["r_but ","But de l'action (nom ou verbe) "],
["r_symptomes ","Symptômes de la maladie : myxomatose => yeux rouges, rougeole => boutons, ..."], 
["r_prop ","Pour le terme donné, il faut indiquer les noms de propriétés pertinents (par exemple pour 'voiture', le 'prix', la 'puissance', la 'longueur', le 'poids'. On ne met que des noms et pas des adjectifs). "], 
["r_incompatible ","Relation d'incompatibilité, ne doivent pas être présents ensembles. Par exemple, alcool r_incompatible antibiotique. "], 
["r_inhib ","Relation d'inhibition, le terme inhibe les termes suivants... ce terme a tendance à exclure le terme associé. "], 
]